name: Android CI

on:
  push:
    branches: [ master ]
    paths:
    - android-app/**
    - !android-app/app/src/main/assets/**

jobs:
  build:

    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
        working-directory: android-app

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew assembleDebug
