name: Android CI

on:
  push:
    branches: [ master ]
    paths:
    - 'android-app/**'
    - '!android-app/app/src/main/assets/**'

jobs:
  build:

    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
        working-directory: android-app

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Install NDK
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.3.6528147" --sdk_root=${ANDROID_SDK_ROOT}
    - name: Build with Gradle
      run: ./gradlew assembleDebug
