name: Desktop CI

on:
  push:
    branches: [ master ]
    paths:
    - 'desktop-app/**'
    - '!desktop-app/resources/**'

jobs:
  build:

    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: desktop-app

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Build with Gradle
      run: ./gradlew assemble
